version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hackideasDB
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  hack-ideas-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hack-ideas-app
    ports:
      - "3000:3000"
 